### ISSUE TITLE
Add font and size options for inline editing

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-frontpage#72] opened 2018-08-22 22:19 UTC
There is already an issue related when pasting content in the DSC tracker
https://github.com/dictyBase/Dicty-Stock-Center/issues/171

But in general, we have pages with **different fonts and sizes** we need tools for that. One of the most important text editing tools.

I just edited this page and look at the steps bottom of page!
https://testdb.dictybase.org/stockcenter/information/order
I edited  this page as our orders now take longer to turn around and I decided to edit the new page instead of the old and hope we switch soon.

Thanks!

**Comment by wildlifehexagon** [comment] 2018-08-23 18:37
Related to #38 

The Stock Center uses a different editor than the frontpage. It may be in our best interest to use the same on both apps, especially since the frontpage editor is the more robust of the two.

**Comment by wildlifehexagon** [comment] 2018-09-13 22:27
Closing this since it is a dupe of #84

**Closed by wildlifehexagon** 2018-09-13 22:27 UTC
Labels: enhancement
