### ISSUE TITLE
Link to new front page from dictyBase icon

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-frontpage#94] opened 2018-09-04 21:13 UTC
From the dictyBase icon on the upper left, I think we should not link to the current old database. Lets stay in the new. It's especially annoying when on any other page than the new front page that when you click you go back to the old.

**Comment by wildlifehexagon** [comment] 2018-09-05 14:50
This will be fixed with the latest releases of the other web apps. The issue is that the live versions of the other web apps are still using an old header-footer version, and they simply need to be updated to the most recent one.

**Comment by wildlifehexagon** [comment] 2018-09-17 22:04
I have updated all of our web apps to the newest version of the header-footer. When their new releases go live, this change will go into effect.

**Closed by wildlifehexagon** 2018-09-17 22:04 UTC
Labels: enhancement
